---
output: html_document
editor_options: 
  chunk_output_type: console
---

`greedy2`
is also described in
(@meszkaMaximalPartialRoom2021).

`greedy2`
iterates through all pairs in order
placing the next pair in the first available cell
not violating the conditions of being a partial
Room square.

```{r greedy2_alg}
n <- 10

tic()
# iterate through pairs in given order
R <- expand_grid(row = 1:(n - 1), col = 1:(n - 1)) %>%
  mutate(first = as.integer(NA), second = as.integer(NA)) %>%
  mutate(avail = list(0:(n - 1))) %>%
  greedy2()
toc()
```

```{r greedy_2_is_maximal_room}
# is R a maximal partial Room square?
is_maximal_proom(R)
```

```{r greedy_2_plot, echo=FALSE, message=FALSE, fig.width=9, fig.height=9}
nf <- n_filled_cells(R)
v <- volume(R)

ggplot(data = R %>% pivot_wider(), aes(col, row)) +
  geom_segment(data = grid_lines(n-1, n-1), aes(x = x, y = y, xend = xend, yend = yend), size = .1) +
  geom_text(data = R %>% pivot_wider() %>% filter(!is.na(first)), aes(label = paste(first, second, sep = ","))) +
  scale_y_reverse() +
  coord_fixed() + 
  theme_void() +
  theme(
    legend.position  = "none"
  ) +
  labs(
    title = glue("A maximal partial Room square of order {n}"),
    subtitle = glue("Number of filled cells: {nf}, Volume: {v}.")
  )
```
